name = "api"
main = "src/index.ts"
compatibility_date = "2023-10-30"
node_compat = true

[env.development]
[env.development.vars]
  database_id = "$database_id"
  LOGGING="debug"

  [[env.development.d1_databases]]
  binding = "DB"
  database_name = "vaella-db"
  database_id = "$database_id"

[env.production]
[env.production.vars]
  database_id = "$database_id"
  LOGGING="info"

  [[env.production.d1_databases]]
  binding = "DB"
  database_name = "vaella-db"
  database_id = ""

